App views
Mucyosoda/blog_app pull request #5
Opened 2022-03-30 12:25 UTC by Mucyosoda

**Blog app - views**

Implement the design from the sneak peek wireframes
Use methods

2022-03-30 13:00 UTC, rloterh requested changes
Hi Mucyo, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Good Points 👍  
- Descriptive Pull Request
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 13:00 UTC, rloterh commented on app/models/post.rb
Running **DB migration is failing** on multiple attempts:
- [x]  Kindly consider updating a table instead of creating a double tables. 

**Migration error 1:**
![image](https://user-images.githubusercontent.com/12745474/160837962-55b8c619-cea7-498e-8cce-9cb8f6c34e9c.png)

- [x] Kindly ensure that proper associations exist among your models

**Migration error 2:**
![image](https://user-images.githubusercontent.com/12745474/160839028-e89f67ef-801b-4146-9356-2082f66945ad.png)

2022-03-30 13:29 UTC, Emmyn5600 requested changes
Hi @Mucyosoda 

Good job so far! I know you have worked hard on making this milestone however, There are some issues that you still need to work on to go to the next project but you are almost there!

## To highlight :champagne:

- All linters are passing :heavy_check_mark:
- Good PR description :heavy_check_mark:


## Required Changes :recycle:

- [ ]  Running DB migration is failing on multiple attempts.

![image](https://user-images.githubusercontent.com/55635977/160845271-64d16b9f-6824-4c08-a49c-26ffb77c4753.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!:clap::clap::clap:

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 14:52 UTC, dasileker requested changes
### **Hi @Mucyosoda ,** 

### **Great work on making the changes 👏** 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## **Suggested changes**
_Check the comments under the review._

- Please remove the duplicated migration files as the previous TSEs requested. you have a double everything, remove the old ones and keep the new ones.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-30 18:34 UTC, Davidosky007 reviewed
Hello @Mucyosoda  👋,

_This is an additional review as a result of the second opinion request._

- @rloterh @Emmyn5600 @dasileker Kindly note that for cases like this where you encounter errors during installation as a result you are not able to perform a proper review on the project requirements you should invalidate, give reasons and probaly solutions to the cause of the errors. 

- As these project havent been reviwed properly i will give you one as i can see the duplicate migartion error has been resloved 👍 
- Kindly work on the following below⬇️ as i get some errors trying mock the wireframe functions
- I get this error when i click on the see all posts button ( example URL: http://localhost:3000/users/2/posts) as seen in the [wirefarme diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)
![image](https://user-images.githubusercontent.com/52497246/160905365-66eec484-39d8-45f3-a693-d93eac12485f.png)

- When i click on a particular post by the same user i get an error ( example URL: http://localhost:3000/users/2/posts/3) as seen in the [wirefarme diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md)
![image](https://user-images.githubusercontent.com/52497246/160906405-22ce2ece-5f82-4c75-9e9f-0650e1eb7917.png)

Please fix all these issues and request another Second opinion and your project should be approved manually 🙏 



Keep rocking 🚀!

2022-03-31 12:24 UTC, Davidosky007 reviewed
Hello @Mucyosoda  👋,

_This is an additional review as a result of the second opinion request._

Kindly fix the issues i pointed out [Here](https://github.com/Mucyosoda/blog_app/pull/5#pullrequestreview-926555462) earlier as they still persist, do this and request another SO so that your project can be approved manually 

Please note that since we will approve it manually so this could take a few hours!

Keep rocking 🚀!

2022-03-31 19:42 UTC, sinansevgi reviewed
Hello @Mucyosoda  👋,

_This is an additional review as a result of the second opinion request._

I can see that you have made all the changes requested by the @Davidosky007, 
Great Work 👍 

As this was the only reason that your project was not approved it will be **approved** as soon as possible.
Please note that since we will approve it manually so this could take a **few hours**!

Keep rocking 🚀!

2022-04-01 09:22 UTC, merged